require("core.plugins")
require("core.mappings")
require("core.misc")

require("plugins.autopairs")
require("plugins.neotree")
require("plugins.mason")
require("plugins.lspconfig")
require("plugins.cmp")
require("plugins.treesitter")
require("plugins.flutter_tools")
require("plugins.none_ls")
require("plugins.toggleterm")
require("plugins.lualine")
require("plugins.lsp_signature")
require("plugins.flutter_bloc")
require("plugins.venv_selector")
require("plugins.autotag")
require("plugins.surround")
require("plugins.telescope")

require("snippets")
